application: eastcobblacrosse
version: 1
runtime: python27
api_version: 1
threadsafe: no


handlers:
- url: /stylesheets
  static_dir: stylesheets
- url: /scripts
  static_dir: scripts
- url: /images
  static_dir: images
- url: /gallery
  static_dir: gallery
- url: /fonts
  static_dir: fonts

- url: /_ah/mail/roster@.*eastcobblacrosse\.appspotmail\.com
  script: hog_functions.EmailRoster.app
  login: admin

  
- url: /news/.*
  script: hog_controllers.NewsController.app
  
- url: /contact/.*
  script: hog_controllers.ContactController.app
  
- url: /about/.*
  script: hog_controllers.AboutController.app

- url: /userManagement/.*
  script: hog_controllers.UserManagementController.app

- url: /events/.*
  script: hog_controllers.EventController.app

- url: /.*
  script: hog_controllers.IndexController.application

  
libraries:
- name: webapp2
  version: latest  
- name: jinja2
  version: latest
- name: pycrypto
  version: latest

    
inbound_services:
- mail